- name: Install python3-aexpect first
  dnf:
    name: python3-aexpect
    state: present
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
