# Install dependencies
- name: Install Basic Depedencies on Red Hat (like) systems specific to pip method
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-pip
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
    - method == 'pip'

- name: Install Avocado-VT Depedencies on Red Hat (like) systems
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - gcc
    - nc
    - python3-netaddr
    - python3-netifaces
    - python3-aexpect
    - qemu-img
    - qemu-kvm
    - tcpdump
    - iproute
    - iputils
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
