# Install dependencies
- name: Install Basic Depedencies on Red Hat (like) systems specific to pip method
  package:
    name: python3-pip
    state: latest
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
    - method == 'pip'

- name: Install Avocado-VT Depedencies on Red Hat (like) systems
  dnf:
    name:
     - git
     - gcc
     - nc
     - python3-netaddr
     - python3-netifaces
     - qemu-img
     - qemu-kvm
     - tcpdump
     - iproute
     - iputils
    state: latest
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
