---
- name: Install EPEL on Red Hat systems
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
  when:
    # This should work on both RHEL, CentOS, Scientific Linux, etc
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution'] != "Fedora"
      
- name: Install Basic Depedencies on Red Hat (like) systems
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3-pip
    - git
  when: ansible_facts['distribution_file_variety'] == "RedHat"
