# Official + Copr Modules disable
- name: Disable Fedora module to avoid conflict
  ini_file:
    path: /etc/yum.repos.d/fedora-modular.repo
    section: fedora-modular
    option: enabled
    value: '0'
  when:
    - method == 'official' or method == 'copr'
    - ansible_facts['distribution'] == "Fedora"

- name: Disable Fedora module updates to avoid conflict
  ini_file:
    path: /etc/yum.repos.d/fedora-updates-modular.repo
    section: updates-modular
    option: enabled
    value: '0'
  when:
    - method == 'official' or method == 'copr'
    - ansible_facts['distribution'] == "Fedora"

# Official repos
- name: Install Avocado EPEL Official Releases repo
  yum_repository:
    name: avocado
    description: Avocado EPEL Official Releases repo
    baseurl: https://avocado-project.org/data/repos/epel-$releasever-noarch/
    gpgcheck: yes
    gpgkey: https://avocado-project.org/data/repos/crosa_redhat_com.gpg
  when:
    - method == 'official'
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: Install Avocado Fedora Official Releases repo
  yum_repository:
    name: avocado
    description: Avocado Fedora Official Releases repo
    baseurl: https://avocado-project.org/data/repos/fedora-$releasever-noarch/
    gpgcheck: yes
    gpgkey: https://avocado-project.org/data/repos/crosa_redhat_com.gpg
  when:
    - method == 'official'
    - ansible_facts['distribution'] == "Fedora"

# Copr repos (Avocado)
- name: Avocado EPEL Copr repo
  yum_repository:
    name: avocado-latest
    description: Copr repo for avocado-latest
    baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-latest/epel-$releasever-$basearch/
    gpgcheck: no
  when:
    - method == 'copr'
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution'] != "Fedora"

- name: Avocado Fedora Copr repo
  yum_repository:
    name: avocado-latest
    description: Copr repo for avocado-latest
    baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-latest/fedora-$releasever-$basearch/
    gpgcheck: no
  when:
    - method == 'copr'
    - ansible_facts['distribution'] == "Fedora"

# Copr repos (Avocado-VT)
- name: Avocado-VT EPEL Copr repo
  yum_repository:
    name: avocado-vt-latest
    description: Copr repo for avocado-vt-latest
    baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-vt-latest/epel-7-$basearch/
    gpgcheck: no
  when:
    - method == 'copr'
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - ansible_facts['distribution'] != "Fedora"
    - ansible_facts['distribution_major_version'] == "7"
    - avocado_vt|default(false)|bool == true

- name: Avocado-VT Fedora Copr repo
  yum_repository:
    name: avocado-vt-latest
    description: Copr repo for avocado-vt-latest
    baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-vt-latest/fedora-$releasever-$basearch/
    gpgcheck: no
  when:
    - method == 'copr'
    - ansible_facts['distribution'] == "Fedora"
    - avocado_vt|default(false)|bool == true
