#!/usr/bin/env python3

# Minimal job that runs an also minimal executable test

import os
import sys

from avocado.core.job import Job
from avocado.core.suite import TestSuite

config = {
    'resolver.references': [
        os.path.join(os.path.dirname(__file__), 'tests', 'pass'),
        os.path.join(os.path.dirname(__file__), 'tests', 'passtest.py')
        ]
    }

suite = TestSuite.from_config(config)
with Job(config, [suite]) as j:
    sys.exit(j.run())
