redhat_version_task:
    version_script:
       - python3 -c 'import setuptools' || dnf -y install python3 python3-setuptools
       - python3 setup.py develop --user
       - python3 -m avocado --version
    container:
        matrix:
          - image: fedora:33
          - image: fedora:34
          - image: registry.access.redhat.com/ubi8/ubi

fedora_develop_install_uninstall_task:
    develop_install_uninstall_script:
       - python3 -c 'import setuptools' || dnf -y install python3 python3-setuptools
       - python3 setup.py develop --user
       - test `python3 -m avocado plugins | grep ^html | wc -l` -eq "3"
       - test `python3 -m avocado plugins | grep ^robot | wc -l` -eq "2"
       - python3 setup.py develop --user --uninstall
       - python3 setup.py clean --all
       - python3 setup.py develop --user --skip-optional-plugins
       - python3 -m avocado --version
       - test `python3 -m avocado plugins | grep ^html | wc -l` -eq "0"
       - test `python3 -m avocado plugins | grep ^robot | wc -l` -eq "0"
    container:
      image: fedora:34

redhat_egg_task:
    egg_script:
       - python3 -c 'import setuptools' || dnf -y install python3 python3-setuptools
       - python3 setup.py bdist_egg
       - mv dist/avocado_framework-*egg /tmp
       - python3 setup.py clean --all
       - python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run --test-runner=runner /bin/true
       - cd /tmp
       - python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run --test-runner=runner /bin/true
    container:
        matrix:
          - image: fedora:33
          - image: fedora:34
          - image: registry.access.redhat.com/ubi8/ubi

debian_version_task:
    version_script:
       - python3 --version || (apt update && apt -y install python3 python3-setuptools ca-certificates)
       - python3 setup.py develop --user
       - python3 -m avocado --version

    container:
        matrix:
          - image: debian:10.10
          - image: debian:11.0
          - image: ubuntu:18.04
          - image: ubuntu:20.04

debian_egg_task:
    egg_script:
       - python3 --version || (apt update && apt -y install python3 python3-setuptools)
       - python3 setup.py bdist_egg
       - mv dist/avocado_framework-*egg /tmp
       - python3 setup.py clean --all
       - python3 -c 'import sys; import glob; sys.path.insert(0, glob.glob("/tmp/avocado_framework-*.egg")[0]); from avocado.core.main import main; sys.exit(main())' run --test-runner=runner /bin/true
       - cd /tmp
       - python3 -c 'import sys; from pkg_resources import require; require("avocado-framework"); from avocado.core.main import main; sys.exit(main())' run --test-runner=runner /bin/true
    container:
        matrix:
          - image: debian:10.10
          - image: debian:11.0
          - image: ubuntu:18.04
          - image: ubuntu:20.04

fedora_selftests_task:
    selftests_script:
       - make develop
       - PATH=$HOME/.local/bin:$PATH LANG=en_US.UTF-8 AVOCADO_CHECK_LEVEL=0 python3 selftests/check.py --skip --static-checks
    container:
        matrix:
          - image: quay.io/avocado-framework/avocado-ci-fedora-33
