specfile_path: python-avocado.spec
downstream_package_name: python-avocado
srpm_build_deps: []
jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
      - fedora-all
      - centos-stream-9
      - epel-9
      - fedora-41-aarch64
      - fedora-41-ppc64le
      - fedora-41-s390x
      enable_net: False
