# This Makefile contains snippets used on other Makefiles

ifndef PYTHON
PYTHON=$(shell which python3 2>/dev/null || which python 2>/dev/null)
endif

ifndef VERSION
VERSION=$(shell $(PYTHON) setup.py --version 2>/dev/null)
endif

ifndef PYTHON_DEVELOP_ARGS
PYTHON_DEVELOP_ARGS=$(shell if ($(PYTHON) setup.py develop --help 2>/dev/null | grep -q '\-\-user'); then echo "--user"; else echo ""; fi)
endif

pip:
	$(PYTHON) -m pip --version || $(PYTHON) -m ensurepip $(PYTHON_DEVELOP_ARGS)
