from autotest.client.shared import distro

DEFAULT_MACHINE_TYPE = "i440fx"
DEFAULT_GUEST_OS = "JeOS.19"


def get_default_guest_os_info():
    """
    Gets the default asset and variant information depending on host OS
    """
    os_info = {'asset': 'jeos-19-64', 'variant': DEFAULT_GUEST_OS}

    detected = distro.detect()
    if detected.name == 'fedora' and int(detected.version) >= 20:
        os_info = {'asset': 'jeos-20-64', 'variant': 'JeOS.20'}

    return os_info

migrate_params = {'_name_map_file': {'guest-hw.cfg': '(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net',
                                     'guest-os.cfg': 'Linux.JeOS.20.x86_64',
                                     'machines.cfg': 'i440fx',
                                     'subtests.cfg': '(subtest=type_specific).(subtest=io-github-autotest-qemu).(subtest=migrate).default.tcp',
                                     'tests.cfg': 'qemu_kvm_jeos_quick'},
                  '_short_name_map_file': {'guest-hw.cfg': 'filesystem.no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net',
                                           'guest-os.cfg': 'Linux.JeOS.20.x86_64',
                                           'machines.cfg': 'i440fx',
                                           'subtests.cfg': 'type_specific.io-github-autotest-qemu.migrate.default.tcp',
                                           'tests.cfg': 'qemu_kvm_jeos_quick'},
                  'auto_cpu_model': 'yes',
                  'backup_dir': 'images/',
                  'backup_image': 'no',
                  'backup_image_on_check_error': 'no',
                  'boot_menu': 'off',
                  'boot_once': 'c',
                  'boot_order': 'cdn',
                  'cdrom_check_cdrom_pattern': '/dev/cdrom-\\w+|/dev/cdrom\\d*',
                  'cdrom_get_cdrom_cmd': 'ls /dev/cdrom*',
                  'cdrom_test_cmd': 'dd if=%s of=/dev/null bs=1 count=1',
                  'cdroms': 'cd1',
                  'check_image': 'yes',
                  'chk_usb_info_cmd': 'lsusb -v',
                  'connect_uri': 'default',
                  'convert_ppm_files_to_png': 'no',
                  'cpu_chk_cmd': 'ls /sys/devices/system/cpu | egrep -c "cpu[0-9]+$"',
                  'cpu_model_flags': '',
                  'dep': ['qemu_kvm_jeos_quick.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.JeOS.20.x86_64.i440fx.(subtest=type_specific).install',
                          'qemu_kvm_jeos_quick.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.JeOS.20.x86_64.i440fx.(subtest=type_specific).setup',
                          'qemu_kvm_jeos_quick.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.JeOS.20.x86_64.i440fx.(subtest=type_specific).image_copy',
                          'qemu_kvm_jeos_quick.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.JeOS.20.x86_64.i440fx.(subtest=type_specific).unattended_install.cdrom'],
                  'deviceid_str': '%s:%s',
                  'display': 'vnc',
                  'drive_format': 'virtio',
                  'drive_index_cd1': '1',
                  'drive_index_image1': '0',
                  'drive_rerror_image1': '',
                  'drive_werror_image1': '',
                  'enable_msix_vectors': 'yes',
                  'encode_video_files': 'yes',
                  'file_transfer_client': 'scp',
                  'file_transfer_port': '22',
                  'guest_port_remote_shell': '22',
                  'host_setup_flag': 1,
                  'image_backend': 'filesystem',
                  'image_boot': 'yes',
                  'image_chain': '',
                  'image_clone_command': 'cp --reflink=auto %s %s',
                  'image_format': 'qcow2',
                  'image_name': 'images/jeos-20-64',
                  'image_raw_device': 'no',
                  'image_remove_command': 'rm -rf %s',
                  'image_size': '10G',
                  'image_unbootable_pattern': 'Hard Disk.*not a bootable disk',
                  'image_verify_bootable': 'yes',
                  'images': 'image1',
                  'inactivity_treshold': '1800',
                  'inactivity_watcher': 'log',
                  'indirect_image_blacklist': '/dev/hda[\\d]* /dev/sda[\\d]* /dev/sg0 /dev/md0',
                  'install_virtio': 'no',
                  'isa_serials': 'serial0',
                  'iterations': '2',
                  'keep_ppm_files': 'no',
                  'keep_ppm_files_on_error': 'no',
                  'keep_screendumps': 'yes',
                  'keep_screendumps_on_error': 'yes',
                  'keep_video_files': 'yes',
                  'keep_video_files_on_error': 'yes',
                  'kill_timeout': '60',
                  'kill_unresponsive_vms': 'yes',
                  'kill_vm': 'yes',
                  'kill_vm_before_test': 'no',
                  'kill_vm_gracefully': 'yes',
                  'kill_vm_on_error': 'yes',
                  'kvm_default': {'/sys/module/kvm/parameters/allow_unsafe_assigned_interrupts': 'N',
                                  '/sys/module/kvm/parameters/ignore_msrs': 'N',
                                  '/sys/module/kvm/parameters/min_timer_period_us': '500',
                                  '/sys/module/kvm/parameters/mmu_audit': 'N',
                                  '/sys/module/kvm/parameters/tsc_tolerance_ppm': '250'},
                  'local_ip': 'ENTER.YOUR.LOCAL.EXAMPLE.COM',
                  'local_pwd': '',
                  'login_timeout': '360',
                  'machine_type': 'pc',
                  'main_vm': 'virt-tests-vm1',
                  'malloc_perturb': 'yes',
                  'mem': '1024',
                  'mem_chk_cmd': "dmidecode -t 17 | awk -F: '/Size/ {print $2}'",
                  'mem_chk_cur_cmd': 'grep MemTotal /proc/meminfo',
                  'mem_chk_re_str': '[^\\$]([0-9]+)',
                  'mig_timeout': '3600',
                  'migrate_dest_host': 'ENTER.YOUR.DEST.EXAMPLE.COM',
                  'migrate_dest_pwd': 'PASSWORD.DEST.EXAMPLE',
                  'migrate_load_vms': '',
                  'migrate_port': '49152',
                  'migrate_proto': 'tcp',
                  'migrate_shared_storage': 'SHARED_IMAGE.EXAMPLE.COM',
                  'migrate_source_host': 'ENTER.YOUR.SOURCE.EXAMPLE.COM',
                  'migrate_source_pwd': 'PASSWORD.SOURCE.EXAMPLE',
                  'migrate_vms': '',
                  'migration_bg_check_command': 'pgrep tcpdump',
                  'migration_bg_command': 'cd /tmp; nohup tcpdump -q -i any -t ip host localhost',
                  'migration_bg_kill_command': 'pkill -9 tcpdump',
                  'migration_protocol': 'tcp',
                  'migration_test_command': 'help',
                  'monitor_type': 'human',
                  'monitors': 'hmp1',
                  'name': 'qemu_kvm_jeos_quick.(image_backend=filesystem).no_9p_export.smallpages.no_pci_assignable.qcow2.virtio_blk.smp2.virtio_net.Linux.JeOS.20.x86_64.i440fx.(subtest=type_specific).(subtest=io-github-autotest-qemu).(subtest=migrate).default.tcp',
                  'netdev_peer_re': '\\s{2,}(.*?): .*?\\\\\\s(.*?):',
                  'netdst': 'virbr0',
                  'nettype': 'user',
                  'nic_model': 'virtio',
                  'nics': 'nic1',
                  'os_type': 'linux',
                  'os_variant': 'fedora20',
                  'other_tests_dirs': '',
                  'password': '123456',
                  'paused_after_start_vm': 'no',
                  'pci_assignable': 'no',
                  'ping_pong': '1',
                  'product': 'QEMU USB Keyboard',
                  'product_id': '0001',
                  'profilers': 'kvm_stat',
                  'provider': 'io-github-autotest-qemu',
                  'qemu_binary': '/bin/qemu-kvm',
                  'qemu_img_binary': '/bin/qemu-img',
                  'qemu_io_binary': '/bin/qemu-io',
                  'reboot_command': 'shutdown -r now',
                  'redirs': 'remote_shell',
                  'remote_ip': 'ENTER.YOUR.REMOTE.EXAMPLE.COM',
                  'remote_pwd': '',
                  'remote_user': 'root',
                  'restore_image': 'yes',
                  'restore_image_on_check_error': 'no',
                  'run_tcpdump': 'no',
                  'screendump_delay': '5',
                  'screendump_quality': '30',
                  'screendump_temp_dir': '/dev/shm',
                  'screendump_verbose': 'no',
                  'shell_client': 'ssh',
                  'shell_port': '22',
                  'shell_prompt': '^\\[.*\\][\\#\\$]\\s*$',
                  'shortname': 'qcow2.virtio_blk.smp2.virtio_net.JeOS.20.x86_64.io-github-autotest-qemu.migrate.tcp',
                  'shutdown_command': 'shutdown -h now',
                  'skip_cluster_leak_warn': 'no',
                  'skip_image_check_during_running': 'no',
                  'skip_image_processing': 'no',
                  'smp': '2',
                  'start_vm': 'yes',
                  'status_test_command': 'echo $?',
                  'store_vm_register': 'yes',
                  'strict_mode': 'no',
                  'subtest': 'io-github-autotest-qemu.migrate',
                  'take_regular_screendumps': 'yes',
                  'test_timeout': '14400',
                  'type': 'migration',
                  'url_auto_ip': '192.168.122.1',
                  'usb_bus': 'usbtest.0',
                  'usb_controller': 'uhci',
                  'usb_controller_tablet1': 'uhci',
                  'usb_devices': 'tablet1 testdev',
                  'usb_max_port': '2',
                  'usb_max_port_usbtest': '2',
                  'usb_type': 'usb-kbd',
                  'usb_type_tablet1': 'usb-tablet',
                  'usb_type_usb1': 'ich9-usb-uhci1',
                  'usb_type_usbtest': 'piix3-usb-uhci',
                  'usbs': 'usb1 usbtest',
                  'use_autostart': 'no',
                  'use_check_cpu': 'yes',
                  'use_debug': 'yes',
                  'use_no_reboot': 'no',
                  'use_os_type': 'yes',
                  'use_os_variant': 'no',
                  'use_virt_install_wait': 'no',
                  'used_cpus': '2',
                  'used_mem': '1024',
                  'username': 'root',
                  'vcpu_thread_pattern': 'thread_id.?[:|=]\\s*(\\d+)',
                  'vendor': 'Adomax Technology Co., Ltd',
                  'vendor_id': '0627',
                  'vfd_size': '1440k',
                  'vga': 'std',
                  'virt_install_wait_time': '300',
                  'virt_test_type': 'qemu',
                  'vm_arch_name': 'x86_64',
                  'vm_register_delay': '5',
                  'vm_type': 'qemu',
                  'vms': 'virt-tests-vm1',
                  'vnc_autoport': 'yes'}

boot_params = migrate_params


def params():
    return migrate_params
