#!/bin/bash
GR=0
run_rc() {
    echo "Running '$1'"
    $1
    if [ $? != 0 ]; then
        GR=1
    fi
}
run_rc 'inspekt lint'
echo ""
run_rc 'inspekt indent'
echo ""
run_rc 'inspekt style'
echo ""
run_rc 'selftests/run selftests/all'
exit ${GR}
