#!/usr/bin/env python

import sys

from selftests import test_suite


if __name__ == '__main__':
    def iter_or_id(arg):
        if hasattr(arg, '__iter__'):
            for inner in arg:
                iter_or_id(inner)
        else:
            print(arg.id())
    try:
        iter_or_id(test_suite())
        sys.exit(0)
    except Exception:
        sys.exit(1)
