#!/bin/bash

# number of infringements found
RESULT=0

echo -n "avocado.core imports from examples/tests: "
COUNT=`git grep -E '^(import avocado\.core.*|from avocado\.core(.*)import)' examples/tests | wc -l`
(( RESULT = RESULT + COUNT ))
echo "$COUNT"

echo -n "non-relative avocado imports from avocado/core: "
COUNT=`git grep -E '^(import avocado\..*|from avocado(.*)import)' avocado/core | wc -l`
(( RESULT = RESULT + COUNT ))
echo "$COUNT"

echo -n "avocado imports from avocado/utils: "
COUNT=`git grep -E '^(import avocado\\.*|from avocado(.*)import)' avocado/utils | wc -l`
(( RESULT = RESULT + COUNT ))
echo "$COUNT"

if [ "$RESULT" -ne 0 ]; then
    echo "ERROR: $RESULT module boundary infringements found"
else
    echo "PASS: no module boundary infringement(s) found"
fi
exit $RESULT
