#!/usr/bin/env python3

from avocado.core import nrunner


class FooRunner(nrunner.BaseRunner):
    def run(self):
        yield self.prepare_status('started')
        yield self.prepare_status('finished', {'result': 'pass'})


class RunnerApp(nrunner.BaseRunnerApp):
    PROG_NAME = 'avocado-runner-foo'
    PROG_DESCRIPTION = '*EXPERIMENTAL* N(ext) Runner for tests foo'
    RUNNABLE_KINDS_CAPABLE = {'foo': FooRunner}


def main():
    nrunner.main(RunnerApp)


if __name__ == '__main__':
    main()
