#!/usr/bin/env python3

from avocado.core import nrunner
from avocado.core.runners.utils import messages


class FooRunner(nrunner.BaseRunner):
    def run(self):
        yield messages.get_started_message()
        yield messages.get_finished_message('pass')


class RunnerApp(nrunner.BaseRunnerApp):
    PROG_NAME = 'avocado-runner-foo'
    PROG_DESCRIPTION = '*EXPERIMENTAL* N(ext) Runner for tests foo'
    RUNNABLE_KINDS_CAPABLE = {'foo': FooRunner}


def main():
    nrunner.main(RunnerApp)


if __name__ == '__main__':
    main()
