---
- name: Install Avocado plugins using RPM
  dnf:
    name:
      - python3-avocado-plugins-golang
      - python3-avocado-plugins-output-html
      - python3-avocado-plugins-result-upload
      - python3-avocado-plugins-varianter-cit
      - python3-avocado-plugins-varianter-pict
      - python3-avocado-plugins-varianter-yaml-to-mux
    state: latest

- name: Install the Avocado VT plugin using RPM
  dnf:
    name: python3-avocado-vt
    state: latest
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
    - method == 'official'

- name: Install the Avocado VT plugin using RPM
  dnf:
    name: python3-avocado-plugins-vt
    state: latest
  when:
    - ansible_facts['distribution_file_variety'] == "RedHat"
    - avocado_vt|default(false)|bool == true
    - method == 'copr'
