#!/usr/bin/env python
import os
import sys

# simple magic for using scripts within a source tree
basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if os.path.isdir(os.path.join(basedir, 'avocado')):
    sys.path.append(basedir)

import avocado

if __name__ == '__main__':
    app = avocado.cli.app.AvocadoRunnerApp()
    app.run()
