name: Version
description: Installs and run avocado --version
runs:
  using: composite
  steps:
    - name: Install and run avocado --version
      shell: sh
      run: |
        export PIP_BREAK_SYSTEM_PACKAGES=1
        python3 -m pip install --user -U pip
        python3 -m pip install --user -e .
        python3 -m avocado --version
