[sysinfo]
sudo_commands = dmidecode,fdisk
# Add any other commands that require sudo here, separated by commas.
sudo_for_distros = uos,deepin
# Add any other operating system that require sudo here, separated by commas.
