#!/bin/sh -e
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See LICENSE for more details.
#
# Copyright: Red Hat Inc. 2016
#
# This script restores the original settings of the systemwide kernel
# core pattern once the job finishes running tests
#

if [ -z $AVOCADO_JOB_LOGDIR ]; then
   exit 1
fi

BACKUP_CORE_PATTERN="$AVOCADO_JOB_LOGDIR/coredumps/.backup_core_pattern"
if [ -f $BACKUP_CORE_PATTERN ]; then
    cat $BACKUP_CORE_PATTERN > /proc/sys/kernel/core_pattern
    rm $BACKUP_CORE_PATTERN
fi
