name: Ansible deployment test

on:
  schedule:
    - cron: "0 5 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  podman:
    name: Ansible (${{matrix.extra}})
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    env:
      RUN_BEFORE: 'dnf install -y git ansible'
      GIT_URL: 'https://github.com/${{github.repository}}'
      INVENTORY: 'selftests/deployment/inventory'
      PLAYBOOK: 'selftests/deployment/deployment.yml'
    strategy:
      matrix:
        extra: ["method=pip", "method=copr", "method=official", "method=pip avocado_vt=true", "method=copr avocado_vt=true"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Install Ansible
        run: dnf install -y git ansible
      - name: Run Ansible playbook
        run:  ansible-pull -v -U ${{env.GIT_URL}} -i ${{env.INVENTORY}} -c local ${{env.PLAYBOOK}} -e "${{matrix.extra}}"
